### ISSUE TITLE
Suggestion to replace ɣ by χ for the X Kurdish letter

### ISSUE THREAD

**Issue by arya-coding** [kurd-cc/kipa#1]
Silav,

I'm using your library to make text to speech using neural Text-To-Speech.

It appears to me that for the letter X, for example the word " Xwazî" or "Xoşîn"

Translated with your library into : 
Xwazî,ɣwɑːziː
Xoşîn,ɣoːʃiːn

The ɣ IPA character doesn't seems ideal. I have better results using χ 
For instance : 
Xwazî,χwɑːziː
Xoşîn,χoːʃiːn

What do you think ? I'm testing with AWS Polly with the neural voice "Arabic, Gulf, Hala Female", it gives good results.

Spas dikim keko,

**Comment by JagarYousef** [comment]
Hey Arya,

I just checked both, and you're right about this, it should be [χ](https://en.wikipedia.org/wiki/Voiceless_uvular_fricative) not [ɣ](https://en.wikipedia.org/wiki/Voiced_velar_fricative)
Please feel free to do a PR
